<a href="https://colab.research.google.com/github/Ashwini9713/Digital-forensics-/blob/model-lab/exp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Network Scan Detection

This program analyzes network connection records to identify potential horizontal and vertical scanning activities.

**Horizontal Scanning**: A single source IP addresses attempts to connect to the same port on a large number of distinct destination IP addresses.

**Vertical Scanning**: A single source IP address attempts to connect to a large number of distinct ports on a single destination IP address.

In [1]:
import pandas as pd
import random
from collections import defaultdict

# --- 1. Generate Sample Network Connection Data ---
# For demonstration, let's create a synthetic dataset of network connection records.
# In a real scenario, this data would come from log files, network monitors, etc.

def generate_connection_records(num_records=1000):
    records = []
    source_ips = [f'192.168.1.{i}' for i in range(1, 10)]
    dest_ips = [f'10.0.0.{i}' for i in range(1, 50)]
    ports = [21, 22, 23, 25, 80, 139, 443, 3389, 8080]

    # Simulate some normal traffic
    for _ in range(num_records // 2):
        records.append({
            'source_ip': random.choice(source_ips),
            'destination_ip': random.choice(dest_ips),
            'destination_port': random.choice(ports)
        })

    # Simulate horizontal scan (e.g., 192.168.1.5 scanning port 22 on many hosts)
    scanner_h_ip = '192.168.1.5'
    scan_port_h = 22
    for _ in range(50):
        records.append({
            'source_ip': scanner_h_ip,
            'destination_ip': random.choice(dest_ips),
            'destination_port': scan_port_h
        })

    # Simulate vertical scan (e.g., 192.168.1.7 scanning 10.0.0.10 on many ports)
    scanner_v_ip = '192.168.1.7'
    target_v_ip = '10.0.0.10'
    for _ in range(30):
        records.append({
            'source_ip': scanner_v_ip,
            'destination_ip': target_v_ip,
            'destination_port': random.choice(ports)
        })

    return pd.DataFrame(records)

df = generate_connection_records()
display(df.head())
print(f"Generated {len(df)} connection records.")

     source_ip destination_ip  destination_port
0  192.168.1.9      10.0.0.10                25
1  192.168.1.2      10.0.0.44                80
2  192.168.1.4      10.0.0.13                21
3  192.168.1.5      10.0.0.24                22
4  192.168.1.8      10.0.0.27                25

Generated 580 connection records.

In [2]:
# --- 2. Implement Scan Detection Logic ---

def detect_horizontal_scans(df, threshold_hosts=10, threshold_connections_per_host=1):
    horizontal_scans = {}
    # Group by source IP and destination port
    grouped = df.groupby(['source_ip', 'destination_port'])

    for (src_ip, dest_port), group in grouped:
        # Count unique destination IPs contacted by this source on this port
        unique_dest_ips = group['destination_ip'].nunique()

        # Filter out connections where source and destination are the same (self-connections)
        group_filtered = group[group['source_ip'] != group['destination_ip']]

        # Check if the number of unique destination IPs exceeds the threshold
        if unique_dest_ips >= threshold_hosts:
            # Additionally, let's ensure there are at least 'threshold_connections_per_host' attempts to each host to avoid false positives from single, legitimate connections.
            # This can be refined based on specific requirements.
            potential_scan_records = group_filtered.groupby(['destination_ip']).filter(lambda x: len(x) >= threshold_connections_per_host)
            if not potential_scan_records.empty and potential_scan_records['destination_ip'].nunique() >= threshold_hosts:
                horizontal_scans[(src_ip, dest_port)] = potential_scan_records

    return horizontal_scans

def detect_vertical_scans(df, threshold_ports=5, threshold_connections_per_port=1):
    vertical_scans = {}
    # Group by source IP and destination IP
    grouped = df.groupby(['source_ip', 'destination_ip'])

    for (src_ip, dest_ip), group in grouped:
        # Count unique destination ports contacted by this source to this destination
        unique_dest_ports = group['destination_port'].nunique()

        # Filter out connections where source and destination are the same
        group_filtered = group[group['source_ip'] != group['destination_ip']]

        # Check if the number of unique destination ports exceeds the threshold
        if unique_dest_ports >= threshold_ports:
            # Similar to horizontal, ensure multiple attempts or diverse connections if needed
            potential_scan_records = group_filtered.groupby(['destination_port']).filter(lambda x: len(x) >= threshold_connections_per_port)
            if not potential_scan_records.empty and potential_scan_records['destination_port'].nunique() >= threshold_ports:
                vertical_scans[(src_ip, dest_ip)] = potential_scan_records

    return vertical_scans




### Scan Analysis Results

In [3]:
# --- 3. Perform Analysis and Display Results ---

print("\n--- Detecting Horizontal Scans ---")
horizontal_scans_results = detect_horizontal_scans(df, threshold_hosts=5, threshold_connections_per_host=1) # Lower threshold for sample data
if horizontal_scans_results:
    for (src_ip, dest_port), records in horizontal_scans_results.items():
        print(f"\nHORIZONTAL SCAN DETECTED: Source IP '{src_ip}' scanned port '{dest_port}' on {records['destination_ip'].nunique()} unique hosts.")
        print("Supporting records (first 5):")
        display(records.head())
else:
    print("No significant horizontal scans detected.")

print("\n--- Detecting Vertical Scans ---")
vertical_scans_results = detect_vertical_scans(df, threshold_ports=3, threshold_connections_per_port=1) # Lower threshold for sample data
if vertical_scans_results:
    for (src_ip, dest_ip), records in vertical_scans_results.items():
        print(f"\nVERTICAL SCAN DETECTED: Source IP '{src_ip}' scanned destination IP '{dest_ip}' on {records['destination_port'].nunique()} unique ports.")
        print("Supporting records (first 5):")
        display(records.head())
else:
    print("No significant vertical scans detected.")

--- Detecting Horizontal Scans ---

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.1' scanned port '21' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
45   192.168.1.1      10.0.0.31                21
209  192.168.1.1      10.0.0.26                21
241  192.168.1.1      10.0.0.16                21
336  192.168.1.1       10.0.0.2                21
465  192.168.1.1      10.0.0.30                21

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.1' scanned port '23' on 11 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
9    192.168.1.1       10.0.0.7                23
37   192.168.1.1       10.0.0.8                23
60   192.168.1.1      10.0.0.34                23
144  192.168.1.1      10.0.0.42                23
225  192.168.1.1      10.0.0.46                23

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.1' scanned port '80' on 7 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
24   192.168.1.1      10.0.0.45                80
51   192.168.1.1      10.0.0.26                80
134  192.168.1.1      10.0.0.29                80
160  192.168.1.1      10.0.0.36                80
174  192.168.1.1      10.0.0.23                80

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.1' scanned port '443' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
13   192.168.1.1      10.0.0.13               443
71   192.168.1.1      10.0.0.27               443
136  192.168.1.1      10.0.0.48               443
147  192.168.1.1      10.0.0.21               443
481  192.168.1.1      10.0.0.24               443

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.1' scanned port '3389' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
28   192.168.1.1       10.0.0.1              3389
96   192.168.1.1      10.0.0.36              3389
268  192.168.1.1      10.0.0.42              3389
375  192.168.1.1       10.0.0.9              3389
496  192.168.1.1      10.0.0.27              3389

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.2' scanned port '23' on 7 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
30   192.168.1.2      10.0.0.46                23
42   192.168.1.2       10.0.0.9                23
56   192.168.1.2      10.0.0.21                23
81   192.168.1.2       10.0.0.4                23
283  192.168.1.2      10.0.0.33                23

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.2' scanned port '80' on 7 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
1    192.168.1.2      10.0.0.44                80
94   192.168.1.2      10.0.0.12                80
158  192.168.1.2       10.0.0.7                80
219  192.168.1.2      10.0.0.42                80
281  192.168.1.2       10.0.0.4                80

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.2' scanned port '139' on 7 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
14   192.168.1.2       10.0.0.5               139
74   192.168.1.2      10.0.0.47               139
87   192.168.1.2      10.0.0.11               139
217  192.168.1.2      10.0.0.35               139
255  192.168.1.2       10.0.0.8               139

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.2' scanned port '443' on 9 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
80   192.168.1.2      10.0.0.43               443
90   192.168.1.2      10.0.0.48               443
117  192.168.1.2      10.0.0.45               443
142  192.168.1.2      10.0.0.41               443
216  192.168.1.2      10.0.0.15               443

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.2' scanned port '3389' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
7    192.168.1.2       10.0.0.1              3389
61   192.168.1.2      10.0.0.25              3389
261  192.168.1.2       10.0.0.2              3389
352  192.168.1.2      10.0.0.12              3389
398  192.168.1.2      10.0.0.12              3389

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.3' scanned port '21' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
12   192.168.1.3      10.0.0.21                21
98   192.168.1.3      10.0.0.48                21
186  192.168.1.3      10.0.0.22                21
354  192.168.1.3      10.0.0.42                21
468  192.168.1.3      10.0.0.24                21

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.3' scanned port '22' on 8 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
156  192.168.1.3      10.0.0.26                22
167  192.168.1.3      10.0.0.41                22
220  192.168.1.3      10.0.0.48                22
269  192.168.1.3      10.0.0.39                22
279  192.168.1.3      10.0.0.35                22

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.3' scanned port '23' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
40   192.168.1.3      10.0.0.25                23
47   192.168.1.3       10.0.0.1                23
135  192.168.1.3      10.0.0.27                23
364  192.168.1.3      10.0.0.15                23
411  192.168.1.3      10.0.0.26                23

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.3' scanned port '25' on 8 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
62   192.168.1.3       10.0.0.4                25
100  192.168.1.3       10.0.0.3                25
180  192.168.1.3       10.0.0.1                25
199  192.168.1.3      10.0.0.25                25
303  192.168.1.3      10.0.0.31                25

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.3' scanned port '80' on 8 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
8    192.168.1.3      10.0.0.44                80
111  192.168.1.3      10.0.0.24                80
138  192.168.1.3      10.0.0.42                80
243  192.168.1.3      10.0.0.30                80
323  192.168.1.3      10.0.0.39                80

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.3' scanned port '443' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
93   192.168.1.3      10.0.0.28               443
260  192.168.1.3       10.0.0.1               443
319  192.168.1.3      10.0.0.46               443
348  192.168.1.3      10.0.0.23               443
380  192.168.1.3      10.0.0.22               443

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.3' scanned port '3389' on 9 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
121  192.168.1.3      10.0.0.47              3389
152  192.168.1.3       10.0.0.6              3389
183  192.168.1.3      10.0.0.43              3389
190  192.168.1.3      10.0.0.20              3389
202  192.168.1.3       10.0.0.9              3389

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.3' scanned port '8080' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
41   192.168.1.3      10.0.0.27              8080
112  192.168.1.3      10.0.0.46              8080
128  192.168.1.3      10.0.0.26              8080
145  192.168.1.3      10.0.0.36              8080
211  192.168.1.3      10.0.0.26              8080

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.4' scanned port '22' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
26   192.168.1.4      10.0.0.17                22
131  192.168.1.4      10.0.0.24                22
198  192.168.1.4      10.0.0.49                22
228  192.168.1.4      10.0.0.35                22
445  192.168.1.4      10.0.0.45                22

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.4' scanned port '23' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
143  192.168.1.4      10.0.0.44                23
227  192.168.1.4       10.0.0.1                23
276  192.168.1.4      10.0.0.47                23
286  192.168.1.4      10.0.0.20                23
464  192.168.1.4      10.0.0.33                23

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.4' scanned port '25' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
132  192.168.1.4      10.0.0.40                25
181  192.168.1.4       10.0.0.9                25
258  192.168.1.4      10.0.0.25                25
403  192.168.1.4      10.0.0.16                25
409  192.168.1.4      10.0.0.32                25

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.4' scanned port '80' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
99   192.168.1.4      10.0.0.16                80
245  192.168.1.4      10.0.0.25                80
361  192.168.1.4      10.0.0.42                80
412  192.168.1.4      10.0.0.18                80
442  192.168.1.4      10.0.0.40                80

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.4' scanned port '139' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
68   192.168.1.4       10.0.0.3               139
187  192.168.1.4      10.0.0.15               139
201  192.168.1.4      10.0.0.25               139
234  192.168.1.4      10.0.0.48               139
273  192.168.1.4      10.0.0.35               139

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.4' scanned port '443' on 8 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
59   192.168.1.4      10.0.0.12               443
86   192.168.1.4      10.0.0.27               443
127  192.168.1.4      10.0.0.45               443
159  192.168.1.4       10.0.0.4               443
259  192.168.1.4      10.0.0.24               443

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.4' scanned port '3389' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
48   192.168.1.4      10.0.0.45              3389
52   192.168.1.4       10.0.0.5              3389
54   192.168.1.4       10.0.0.5              3389
244  192.168.1.4      10.0.0.20              3389
250  192.168.1.4      10.0.0.40              3389

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.4' scanned port '8080' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
70   192.168.1.4      10.0.0.26              8080
110  192.168.1.4      10.0.0.25              8080
125  192.168.1.4      10.0.0.43              8080
126  192.168.1.4      10.0.0.17              8080
146  192.168.1.4      10.0.0.23              8080

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.5' scanned port '22' on 35 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
3    192.168.1.5      10.0.0.24                22
108  192.168.1.5      10.0.0.29                22
266  192.168.1.5      10.0.0.49                22
377  192.168.1.5       10.0.0.3                22
500  192.168.1.5      10.0.0.27                22

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.5' scanned port '23' on 11 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
83   192.168.1.5      10.0.0.41                23
163  192.168.1.5      10.0.0.42                23
192  192.168.1.5       10.0.0.8                23
207  192.168.1.5      10.0.0.14                23
218  192.168.1.5      10.0.0.13                23

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.5' scanned port '80' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
11   192.168.1.5      10.0.0.13                80
137  192.168.1.5       10.0.0.5                80
188  192.168.1.5      10.0.0.13                80
357  192.168.1.5      10.0.0.44                80
387  192.168.1.5      10.0.0.33                80

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.5' scanned port '139' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
49   192.168.1.5      10.0.0.28               139
66   192.168.1.5      10.0.0.23               139
214  192.168.1.5      10.0.0.42               139
237  192.168.1.5      10.0.0.16               139
379  192.168.1.5      10.0.0.49               139

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.6' scanned port '21' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
82   192.168.1.6      10.0.0.45                21
206  192.168.1.6      10.0.0.22                21
256  192.168.1.6      10.0.0.13                21
274  192.168.1.6      10.0.0.14                21
285  192.168.1.6      10.0.0.29                21

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.6' scanned port '23' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
20   192.168.1.6      10.0.0.27                23
337  192.168.1.6      10.0.0.18                23
349  192.168.1.6      10.0.0.35                23
373  192.168.1.6      10.0.0.32                23
378  192.168.1.6      10.0.0.31                23

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.6' scanned port '25' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
29   192.168.1.6      10.0.0.18                25
32   192.168.1.6       10.0.0.6                25
92   192.168.1.6       10.0.0.6                25
161  192.168.1.6       10.0.0.5                25
321  192.168.1.6      10.0.0.31                25

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.6' scanned port '80' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
15   192.168.1.6      10.0.0.18                80
155  192.168.1.6      10.0.0.32                80
246  192.168.1.6       10.0.0.4                80
299  192.168.1.6      10.0.0.23                80
315  192.168.1.6      10.0.0.14                80

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.6' scanned port '139' on 9 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
10   192.168.1.6      10.0.0.48               139
76   192.168.1.6      10.0.0.28               139
204  192.168.1.6      10.0.0.21               139
265  192.168.1.6      10.0.0.46               139
277  192.168.1.6      10.0.0.10               139

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.6' scanned port '443' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
19   192.168.1.6       10.0.0.8               443
150  192.168.1.6      10.0.0.23               443
253  192.168.1.6      10.0.0.15               443
325  192.168.1.6      10.0.0.45               443
327  192.168.1.6      10.0.0.38               443

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.6' scanned port '3389' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
129  192.168.1.6      10.0.0.10              3389
157  192.168.1.6      10.0.0.18              3389
249  192.168.1.6      10.0.0.25              3389
313  192.168.1.6      10.0.0.22              3389
347  192.168.1.6      10.0.0.11              3389

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.7' scanned port '21' on 7 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
362  192.168.1.7      10.0.0.15                21
376  192.168.1.7       10.0.0.5                21
428  192.168.1.7      10.0.0.14                21
431  192.168.1.7      10.0.0.19                21
437  192.168.1.7      10.0.0.25                21

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.7' scanned port '22' on 8 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
89   192.168.1.7      10.0.0.32                22
123  192.168.1.7      10.0.0.22                22
140  192.168.1.7      10.0.0.46                22
386  192.168.1.7      10.0.0.30                22
392  192.168.1.7      10.0.0.16                22

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.7' scanned port '25' on 11 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
149  192.168.1.7      10.0.0.21                25
154  192.168.1.7      10.0.0.39                25
179  192.168.1.7      10.0.0.47                25
189  192.168.1.7      10.0.0.24                25
195  192.168.1.7       10.0.0.2                25

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.7' scanned port '80' on 11 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
120  192.168.1.7      10.0.0.35                80
141  192.168.1.7       10.0.0.6                80
170  192.168.1.7      10.0.0.45                80
203  192.168.1.7      10.0.0.17                80
223  192.168.1.7      10.0.0.34                80

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.7' scanned port '139' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
101  192.168.1.7      10.0.0.13               139
175  192.168.1.7      10.0.0.38               139
178  192.168.1.7      10.0.0.18               139
185  192.168.1.7      10.0.0.15               139
551  192.168.1.7      10.0.0.10               139

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.7' scanned port '3389' on 9 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
33   192.168.1.7       10.0.0.3              3389
57   192.168.1.7       10.0.0.2              3389
73   192.168.1.7       10.0.0.2              3389
116  192.168.1.7      10.0.0.21              3389
193  192.168.1.7      10.0.0.36              3389

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.7' scanned port '8080' on 7 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
21   192.168.1.7      10.0.0.18              8080
22   192.168.1.7      10.0.0.26              8080
85   192.168.1.7      10.0.0.45              8080
289  192.168.1.7      10.0.0.11              8080
340  192.168.1.7      10.0.0.16              8080

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.8' scanned port '21' on 8 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
27   192.168.1.8      10.0.0.48                21
31   192.168.1.8      10.0.0.37                21
64   192.168.1.8      10.0.0.31                21
275  192.168.1.8      10.0.0.17                21
288  192.168.1.8      10.0.0.30                21

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.8' scanned port '22' on 7 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
67   192.168.1.8      10.0.0.16                22
75   192.168.1.8      10.0.0.44                22
88   192.168.1.8      10.0.0.45                22
103  192.168.1.8      10.0.0.19                22
200  192.168.1.8      10.0.0.30                22

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.8' scanned port '23' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
105  192.168.1.8      10.0.0.38                23
107  192.168.1.8       10.0.0.2                23
205  192.168.1.8      10.0.0.27                23
326  192.168.1.8       10.0.0.4                23
382  192.168.1.8      10.0.0.42                23

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.8' scanned port '25' on 8 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
4    192.168.1.8      10.0.0.27                25
72   192.168.1.8      10.0.0.44                25
104  192.168.1.8      10.0.0.15                25
122  192.168.1.8      10.0.0.44                25
176  192.168.1.8      10.0.0.26                25

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.8' scanned port '80' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
114  192.168.1.8      10.0.0.25                80
215  192.168.1.8      10.0.0.48                80
284  192.168.1.8       10.0.0.5                80
308  192.168.1.8      10.0.0.37                80
460  192.168.1.8      10.0.0.36                80

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.8' scanned port '139' on 7 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
63   192.168.1.8      10.0.0.36               139
77   192.168.1.8      10.0.0.23               139
165  192.168.1.8      10.0.0.13               139
168  192.168.1.8      10.0.0.34               139
300  192.168.1.8      10.0.0.35               139

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.8' scanned port '443' on 7 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
171  192.168.1.8       10.0.0.7               443
210  192.168.1.8      10.0.0.29               443
301  192.168.1.8      10.0.0.29               443
368  192.168.1.8      10.0.0.40               443
389  192.168.1.8      10.0.0.48               443

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.8' scanned port '3389' on 11 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
18   192.168.1.8      10.0.0.26              3389
36   192.168.1.8      10.0.0.34              3389
50   192.168.1.8      10.0.0.41              3389
153  192.168.1.8      10.0.0.49              3389
232  192.168.1.8      10.0.0.25              3389

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.9' scanned port '21' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
254  192.168.1.9       10.0.0.2                21
305  192.168.1.9      10.0.0.40                21
367  192.168.1.9       10.0.0.1                21
432  192.168.1.9      10.0.0.32                21
453  192.168.1.9      10.0.0.23                21

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.9' scanned port '22' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
53   192.168.1.9      10.0.0.34                22
65   192.168.1.9      10.0.0.16                22
162  192.168.1.9      10.0.0.43                22
212  192.168.1.9      10.0.0.43                22
363  192.168.1.9      10.0.0.12                22

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.9' scanned port '23' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
16   192.168.1.9      10.0.0.41                23
102  192.168.1.9      10.0.0.18                23
191  192.168.1.9      10.0.0.29                23
240  192.168.1.9      10.0.0.10                23
402  192.168.1.9      10.0.0.15                23

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.9' scanned port '25' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
0    192.168.1.9      10.0.0.10                25
69   192.168.1.9      10.0.0.48                25
84   192.168.1.9      10.0.0.19                25
95   192.168.1.9      10.0.0.35                25
184  192.168.1.9      10.0.0.49                25

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.9' scanned port '80' on 12 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
5    192.168.1.9      10.0.0.14                80
109  192.168.1.9      10.0.0.47                80
208  192.168.1.9       10.0.0.1                80
252  192.168.1.9      10.0.0.24                80
257  192.168.1.9      10.0.0.27                80

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.9' scanned port '139' on 8 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
139  192.168.1.9       10.0.0.3               139
304  192.168.1.9      10.0.0.48               139
355  192.168.1.9      10.0.0.26               139
374  192.168.1.9      10.0.0.32               139
430  192.168.1.9      10.0.0.41               139

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.9' scanned port '443' on 5 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
25   192.168.1.9      10.0.0.18               443
46   192.168.1.9      10.0.0.31               443
164  192.168.1.9      10.0.0.32               443
177  192.168.1.9       10.0.0.5               443
239  192.168.1.9       10.0.0.9               443

HORIZONTAL SCAN DETECTED: Source IP '192.168.1.9' scanned port '3389' on 6 unique hosts.
Supporting records (first 5):

       source_ip destination_ip  destination_port
34   192.168.1.9      10.0.0.47              3389
58   192.168.1.9       10.0.0.8              3389
124  192.168.1.9      10.0.0.44              3389
222  192.168.1.9      10.0.0.49              3389
233  192.168.1.9       10.0.0.7              3389

--- Detecting Vertical Scans ---

VERTICAL SCAN DETECTED: Source IP '192.168.1.1' scanned destination IP '10.0.0.1' on 4 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
28   192.168.1.1       10.0.0.1              3389
133  192.168.1.1       10.0.0.1                22
148  192.168.1.1       10.0.0.1                25
307  192.168.1.1       10.0.0.1                22
491  192.168.1.1       10.0.0.1               139

VERTICAL SCAN DETECTED: Source IP '192.168.1.2' scanned destination IP '10.0.0.4' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
81   192.168.1.2       10.0.0.4                23
281  192.168.1.2       10.0.0.4                80
391  192.168.1.2       10.0.0.4               139

VERTICAL SCAN DETECTED: Source IP '192.168.1.3' scanned destination IP '10.0.0.1' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
47   192.168.1.3       10.0.0.1                23
180  192.168.1.3       10.0.0.1                25
260  192.168.1.3       10.0.0.1               443

VERTICAL SCAN DETECTED: Source IP '192.168.1.3' scanned destination IP '10.0.0.26' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
128  192.168.1.3      10.0.0.26              8080
156  192.168.1.3      10.0.0.26                22
211  192.168.1.3      10.0.0.26              8080
411  192.168.1.3      10.0.0.26                23

VERTICAL SCAN DETECTED: Source IP '192.168.1.3' scanned destination IP '10.0.0.27' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
41   192.168.1.3      10.0.0.27              8080
135  192.168.1.3      10.0.0.27                23
224  192.168.1.3      10.0.0.27               139

VERTICAL SCAN DETECTED: Source IP '192.168.1.3' scanned destination IP '10.0.0.46' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
112  192.168.1.3      10.0.0.46              8080
312  192.168.1.3      10.0.0.46              3389
319  192.168.1.3      10.0.0.46               443

VERTICAL SCAN DETECTED: Source IP '192.168.1.3' scanned destination IP '10.0.0.48' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
98   192.168.1.3      10.0.0.48                21
220  192.168.1.3      10.0.0.48                22
366  192.168.1.3      10.0.0.48                80

VERTICAL SCAN DETECTED: Source IP '192.168.1.4' scanned destination IP '10.0.0.17' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
26   192.168.1.4      10.0.0.17                22
126  192.168.1.4      10.0.0.17              8080
302  192.168.1.4      10.0.0.17               443

VERTICAL SCAN DETECTED: Source IP '192.168.1.4' scanned destination IP '10.0.0.25' on 5 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
110  192.168.1.4      10.0.0.25              8080
201  192.168.1.4      10.0.0.25               139
245  192.168.1.4      10.0.0.25                80
258  192.168.1.4      10.0.0.25                25
478  192.168.1.4      10.0.0.25                23

VERTICAL SCAN DETECTED: Source IP '192.168.1.4' scanned destination IP '10.0.0.40' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
132  192.168.1.4      10.0.0.40                25
250  192.168.1.4      10.0.0.40              3389
442  192.168.1.4      10.0.0.40                80

VERTICAL SCAN DETECTED: Source IP '192.168.1.4' scanned destination IP '10.0.0.45' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
48   192.168.1.4      10.0.0.45              3389
127  192.168.1.4      10.0.0.45               443
445  192.168.1.4      10.0.0.45                22

VERTICAL SCAN DETECTED: Source IP '192.168.1.5' scanned destination IP '10.0.0.20' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
78   192.168.1.5      10.0.0.20                21
295  192.168.1.5      10.0.0.20                21
450  192.168.1.5      10.0.0.20                23
533  192.168.1.5      10.0.0.20                22

VERTICAL SCAN DETECTED: Source IP '192.168.1.5' scanned destination IP '10.0.0.23' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
23   192.168.1.5      10.0.0.23                25
66   192.168.1.5      10.0.0.23               139
503  192.168.1.5      10.0.0.23                22

VERTICAL SCAN DETECTED: Source IP '192.168.1.5' scanned destination IP '10.0.0.30' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
424  192.168.1.5      10.0.0.30                23
452  192.168.1.5      10.0.0.30              3389
530  192.168.1.5      10.0.0.30                22
545  192.168.1.5      10.0.0.30                22

VERTICAL SCAN DETECTED: Source IP '192.168.1.5' scanned destination IP '10.0.0.35' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
172  192.168.1.5      10.0.0.35               443
247  192.168.1.5      10.0.0.35                21
502  192.168.1.5      10.0.0.35                22
515  192.168.1.5      10.0.0.35                22

VERTICAL SCAN DETECTED: Source IP '192.168.1.5' scanned destination IP '10.0.0.42' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
163  192.168.1.5      10.0.0.42                23
214  192.168.1.5      10.0.0.42               139
480  192.168.1.5      10.0.0.42              3389

VERTICAL SCAN DETECTED: Source IP '192.168.1.5' scanned destination IP '10.0.0.44' on 4 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
357  192.168.1.5      10.0.0.44                80
385  192.168.1.5      10.0.0.44                25
397  192.168.1.5      10.0.0.44                23
531  192.168.1.5      10.0.0.44                22

VERTICAL SCAN DETECTED: Source IP '192.168.1.6' scanned destination IP '10.0.0.18' on 4 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
15   192.168.1.6      10.0.0.18                80
29   192.168.1.6      10.0.0.18                25
157  192.168.1.6      10.0.0.18              3389
337  192.168.1.6      10.0.0.18                23

VERTICAL SCAN DETECTED: Source IP '192.168.1.6' scanned destination IP '10.0.0.23' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
150  192.168.1.6      10.0.0.23               443
242  192.168.1.6      10.0.0.23                22
299  192.168.1.6      10.0.0.23                80

VERTICAL SCAN DETECTED: Source IP '192.168.1.6' scanned destination IP '10.0.0.8' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
19   192.168.1.6       10.0.0.8               443
213  192.168.1.6       10.0.0.8              8080
488  192.168.1.6       10.0.0.8               139

VERTICAL SCAN DETECTED: Source IP '192.168.1.7' scanned destination IP '10.0.0.10' on 9 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
489  192.168.1.7      10.0.0.10                23
550  192.168.1.7      10.0.0.10                22
551  192.168.1.7      10.0.0.10               139
552  192.168.1.7      10.0.0.10                80
553  192.168.1.7      10.0.0.10                25

VERTICAL SCAN DETECTED: Source IP '192.168.1.7' scanned destination IP '10.0.0.16' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
294  192.168.1.7      10.0.0.16                25
340  192.168.1.7      10.0.0.16              8080
392  192.168.1.7      10.0.0.16                22

VERTICAL SCAN DETECTED: Source IP '192.168.1.7' scanned destination IP '10.0.0.2' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
57   192.168.1.7       10.0.0.2              3389
73   192.168.1.7       10.0.0.2              3389
195  192.168.1.7       10.0.0.2                25
395  192.168.1.7       10.0.0.2               443

VERTICAL SCAN DETECTED: Source IP '192.168.1.7' scanned destination IP '10.0.0.45' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
85   192.168.1.7      10.0.0.45              8080
170  192.168.1.7      10.0.0.45                80
197  192.168.1.7      10.0.0.45                23

VERTICAL SCAN DETECTED: Source IP '192.168.1.7' scanned destination IP '10.0.0.5' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
151  192.168.1.7       10.0.0.5               443
351  192.168.1.7       10.0.0.5                25
376  192.168.1.7       10.0.0.5                21

VERTICAL SCAN DETECTED: Source IP '192.168.1.8' scanned destination IP '10.0.0.25' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
114  192.168.1.8      10.0.0.25                80
182  192.168.1.8      10.0.0.25                25
232  192.168.1.8      10.0.0.25              3389

VERTICAL SCAN DETECTED: Source IP '192.168.1.8' scanned destination IP '10.0.0.27' on 4 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
4    192.168.1.8      10.0.0.27                25
205  192.168.1.8      10.0.0.27                23
447  192.168.1.8      10.0.0.27              3389
486  192.168.1.8      10.0.0.27               443

VERTICAL SCAN DETECTED: Source IP '192.168.1.8' scanned destination IP '10.0.0.30' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
200  192.168.1.8      10.0.0.30                22
288  192.168.1.8      10.0.0.30                21
479  192.168.1.8      10.0.0.30                80

VERTICAL SCAN DETECTED: Source IP '192.168.1.8' scanned destination IP '10.0.0.34' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
36   192.168.1.8      10.0.0.34              3389
168  192.168.1.8      10.0.0.34               139
440  192.168.1.8      10.0.0.34                21

VERTICAL SCAN DETECTED: Source IP '192.168.1.8' scanned destination IP '10.0.0.36' on 4 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
63   192.168.1.8      10.0.0.36               139
350  192.168.1.8      10.0.0.36                21
444  192.168.1.8      10.0.0.36               443
460  192.168.1.8      10.0.0.36                80

VERTICAL SCAN DETECTED: Source IP '192.168.1.8' scanned destination IP '10.0.0.44' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
72   192.168.1.8      10.0.0.44                25
75   192.168.1.8      10.0.0.44                22
122  192.168.1.8      10.0.0.44                25
471  192.168.1.8      10.0.0.44              3389

VERTICAL SCAN DETECTED: Source IP '192.168.1.8' scanned destination IP '10.0.0.48' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
27   192.168.1.8      10.0.0.48                21
215  192.168.1.8      10.0.0.48                80
389  192.168.1.8      10.0.0.48               443

VERTICAL SCAN DETECTED: Source IP '192.168.1.9' scanned destination IP '10.0.0.23' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
381  192.168.1.9      10.0.0.23                80
453  192.168.1.9      10.0.0.23                21
498  192.168.1.9      10.0.0.23               139

VERTICAL SCAN DETECTED: Source IP '192.168.1.9' scanned destination IP '10.0.0.26' on 3 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
318  192.168.1.9      10.0.0.26                80
355  192.168.1.9      10.0.0.26               139
469  192.168.1.9      10.0.0.26                25

VERTICAL SCAN DETECTED: Source IP '192.168.1.9' scanned destination IP '10.0.0.32' on 5 unique ports.
Supporting records (first 5):

       source_ip destination_ip  destination_port
164  192.168.1.9      10.0.0.32               443
317  192.168.1.9      10.0.0.32               443
374  192.168.1.9      10.0.0.32               139
396  192.168.1.9      10.0.0.32              8080
432  192.168.1.9      10.0.0.32                21