<a href="https://colab.research.google.com/github/Ashwini9713/Digital-forensics-/blob/model-lab/exp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Reconstructing Recently Used Documents from a Simulated Activity Log

This program will analyze a simulated application activity log to extract key information and identify patterns related to document usage. The log will contain entries with document names, users, application names, access times, and activity types.

In [1]:
import pandas as pd
from datetime import datetime

# Simulate application activity log data
simulated_log_data = """
2023-10-26 10:00:00,user1,report.docx,Word,OPEN
2023-10-26 10:05:30,user2,presentation.pptx,PowerPoint,VIEW
2023-10-26 10:10:15,user1,spreadsheet.xlsx,Excel,EDIT
2023-10-26 10:15:00,user3,report.docx,Word,VIEW
2023-10-26 10:20:45,user1,presentation.pptx,PowerPoint,SAVE
2023-10-26 10:25:00,user2,image.jpg,Photos,OPEN
2023-10-26 10:30:10,user4,report.docx,Word,OPEN
2023-10-26 10:35:00,user1,spreadsheet.xlsx,Excel,CLOSE
2023-10-26 10:40:20,user3,email.msg,Outlook,OPEN
2023-10-26 10:45:00,user2,image.jpg,Photos,EDIT
2023-10-26 10:50:30,user5,presentation.pptx,PowerPoint,OPEN
2023-10-26 10:55:00,user1,report.docx,Word,SAVE
"""

# Function to parse the log data into a pandas DataFrame
def parse_log(log_data):
    lines = log_data.strip().split('\n')
    records = []
    for line in lines:
        parts = line.split(',')
        if len(parts) == 5:
            access_time_str, user, document, application, activity_type = parts
            records.append({
                'access_time': datetime.strptime(access_time_str, '%Y-%m-%d %H:%M:%S'),
                'user': user,
                'document': document,
                'application': application,
                'activity_type': activity_type
            })
    return pd.DataFrame(records)

# Parse the simulated log data
df_log = parse_log(simulated_log_data)

print("Extracted log data:")
display(df_log.head())

Extracted log data:

          access_time   user           document application activity_type
0 2023-10-26 10:00:00  user1        report.docx        Word          OPEN
1 2023-10-26 10:05:30  user2  presentation.pptx  PowerPoint          VIEW
2 2023-10-26 10:10:15  user1   spreadsheet.xlsx       Excel          EDIT
3 2023-10-26 10:15:00  user3        report.docx        Word          VIEW
4 2023-10-26 10:20:45  user1  presentation.pptx  PowerPoint          SAVE

### Analysis: Recently Used Documents

To identify the most recently used documents, we will group the data by document and find the latest `access_time` for each.

In [2]:
# Determine the most recently accessed time for each document
most_recent_access = df_log.groupby('document')['access_time'].max().reset_index()
most_recent_access = most_recent_access.sort_values(by='access_time', ascending=False)

print("\nMost recently accessed documents:")
display(most_recent_access)

Most recently accessed documents:

            document         access_time
3        report.docx 2023-10-26 10:55:00
2  presentation.pptx 2023-10-26 10:50:30
1          image.jpg 2023-10-26 10:45:00
0          email.msg 2023-10-26 10:40:20
4   spreadsheet.xlsx 2023-10-26 10:35:00

### Analysis: Documents Accessed by More Than One User

To find documents accessed by multiple users, we will group the data by document and count the number of unique users for each document.

In [3]:
# Identify documents accessed by more than one user
users_per_document = df_log.groupby('document')['user'].nunique().reset_index()
multi_user_documents = users_per_document[users_per_document['user'] > 1]

print("\nDocuments accessed by more than one user:")
display(multi_user_documents)

Documents accessed by more than one user:

            document  user
2  presentation.pptx     3
3        report.docx     3